# Setup
title:            Ronal Gelvez
tagline:          'Software Developer'
description:      'Software Developer'
url:              https://dev-ron.github.io/
baseurl:          /

author:
  name:           'Ronal Gelvez'
  url:            https://www.linkedin.com/in/ronalgelvez/

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
